# -------------------------------------------------------------
# Githab Actions Part-1 
# Popckov Sergey
# -------------------------------------------------------------

# ===== Название ======
# В отличии от названия файла, название "name" имеет значение,
name: My-Actions-1


# ===== Когда запускать ======
# Контролирует когда будет запускаться этот файл, на "push" или
# на "pull_request" 
on:
  
  # Тут же можно конкретизировать, в какой момент запускать и 
  # для какой ветки. Запускать при событии "push" в ветку "main"
  push:
    branches: [ main ]


# ===== Задания для работы ======
# Тут описаны задания которые будут выполняться при запуске файла,
# задачи могут выполняться как параллельно так и последовательно.
jobs:
  
  
  # Первое задание 
  # Это задача, она может называться как угодно, каждая такая задача
  # запускается на отдельной виртуальной машине, которую создает github 
  # и тут дальше описывается работа для Docker в котором будет выполнятся
  # вся работа этого задания.  
  my_testing:
    # На какой ОС будет запущено задание, к примеру можно запустить на
    # runs-on: ubuntu-latest последней ОС или на указанной точно.
    runs-on: ubuntu-18.04

    # Шаги для работы в задании.   
    steps:
      # Название конкретного шага
      - name: Print Message 1
        # Действие внутри конкретного шага, по сути пишим обычный shell         
        run: echo "Hello World from my_testing"
        

  # Второе задание  
  my_deploy: 
    runs-on: ubuntu-18.04
    steps:
      - name: Print Message 2
        run: echo "Hello World from my_deploy"





